[package]
name = "internet-radio"
version = "0.3.3"
authors = ["Samuel Hicks <SamMHicks@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
crossterm =  { version = "0.16", features = ["event-stream"] }
futures = "0.3"
glib = "0.9"
gstreamer = "0.15"
gstreamer-sys = "0.8"
log = { version = "0.4", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = [ "macros", "rt-threaded", "sync", "time"] }
toml = "0.5"
