FROM rust

ARG CROSS_DEB_ARCH
ARG LINKER_PACKAGE
ARG RUST_TARGET_TRIPLE

RUN dpkg --add-architecture $CROSS_DEB_ARCH
RUN apt-get update && apt-get install --assume-yes $LINKER_PACKAGE libgstreamer1.0-dev:$CROSS_DEB_ARCH libgstreamer-plugins-base1.0-dev:$CROSS_DEB_ARCH libclang-dev
RUN rustup target add $RUST_TARGET_TRIPLE

