FROM rust

RUN dpkg --add-architecture armhf
RUN apt-get update && TZ=Europe/London DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes gcc-arm-linux-gnueabihf libgstreamer1.0-dev:armhf libgstreamer-plugins-base1.0-dev:armhf gstreamer1.0-plugins-base:armhf gstreamer1.0-plugins-good:armhf gstreamer1.0-plugins-bad:armhf gstreamer1.0-plugins-ugly:armhf gstreamer1.0-libav:armhf libgstrtspserver-1.0-dev:armhf libges-1.0-dev:armhf libssl-dev:armhf libclang-dev
RUN rustup target add armv7-unknown-linux-gnueabihf

ENV CARGO_BUILD_TARGET=armv7-unknown-linux-gnueabihf
ENV PKG_CONFIG_SYSROOT_DIR_armv7_unknown_linux_gnueabihf=/
ENV PKG_CONFIG_PATH_armv7_unknown_linux_gnueabihf=/lib/arm-linux-gnueabihf/pkgconfig/
ENV CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
