[package]
name = "rradio-messages"
version = "0.28.1"
authors = ["Samuel Hicks <SamMHicks@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcstr = { version = "1.0", default-features = false, features = [ "serde", "std" ] }
base64 = "0.13"
postcard = { version = "1.0", default-features = false, features = [ "use-std" ] }
serde = { version = "1.0", features = ["derive", "rc"] }
thiserror = "1.0"
