[package]
name = "rradio-messages"
version = "0.25.0"
authors = ["Samuel Hicks <SamMHicks@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcstr = { version = "1.0", features = [ "serde" ] }
base64 = "0.13"
serde = { version = "1.0", features = ["derive", "rc"] }
thiserror = "1.0"
