[package]
name = "rradio"
version = "0.48.0"
authors = [ "Samuel Hicks <SamMHicks@hotmail.co.uk>" ]
edition = "2018"
description = "An internet radio with configurable two digit entry of stations"
readme = "README.md"
homepage = "https://github.com/sammhicks/internet-radio-rs"
repository = "https://github.com/sammhicks/internet-radio-rs"
license = "MIT"
keywords = [ "radio" ]
categories = [ "audio", "internet" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cd = [ "libc" ]
mount = [ "sys-mount", "tempdir" ]
ping = [ "pnet", "pnet_macros_support" ]
production-server = []
usb = [ "mount" ]
web = [ "axum", "tower", "tower-http" ]
default = [ "web" ]

[dependencies]
anyhow = "1.0.68"
askama = "0.11.1"
axum = { version = "0.6.4", default-features = false, features = [ "http1", "json", "ws" ], optional = true }
crossterm =  { version = "0.26.0", features = [ "event-stream" ] }
futures = "0.3.25"
glib = "0.16.7"
gstreamer = "0.19.7"
gstreamer-audio = "0.19.4"
gstreamer-sys = "0.19.4"
humantime-serde = "1.1.1"
pnet = { version = "0.31.0", features = [ "std" ], optional = true }
pnet_macros_support = { version = "0.31.0", optional = true }
pls = "0.2.2"
quick-xml = { version = "0.27.1", features = [ "serialize" ] }
rand = "0.8.5"
reqwest = { version = "0.11.14", default-features = false }
serde = { version = "1.0", features = [ "derive", "rc" ] }
sys-mount = { version = "2.0", optional = true }
tempdir = { version = "0.3", optional = true }
thiserror = "1.0"
tokio = { version = "1.24", features = [ "io-util", "net", "rt-multi-thread", "sync", "time" ] }
toml = "0.7"
tower = { version = "0.4", optional = true }
tower-http = { version = "0.3", features = [ "fs" ], optional = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
url = { version = "2.3", features = [ "serde" ] }

rradio-messages = { path = "../messages", features = [ "async" ] }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true }
